// Generated by scripts/generate-bundled-packs.mjs — do not edit by hand.
import type { BundledPackSource } from '@/services/bundledPacks';

/** Bump when bundled pack contents change so existing installs re-copy them. */
export const BUNDLED_PACKS_VERSION = 1;

export const bundledPacks: BundledPackSource[] = [
  {
    pack: require('./starter-basics/pack.json'),
    files: {
      'tray.png': require('./starter-basics/tray.png'),
      's1.webp': require('./starter-basics/s1.webp'),
      's2.webp': require('./starter-basics/s2.webp'),
      's3.webp': require('./starter-basics/s3.webp'),
      's4.webp': require('./starter-basics/s4.webp'),
      's5.webp': require('./starter-basics/s5.webp'),
      's6.webp': require('./starter-basics/s6.webp'),
    },
  },
];
